### ISSUE TITLE
Using CAC card?

### ISSUE THREAD

**Issue by rorsino** [bramdejager/spcb#100]
Is is possible to use a CAC card with this app ??  Using a CAC card is the only way I can get to my system.

Thanks

**Comment by bramdejager** [comment]
Hi, sorry to hear you are not able to use the tool. I don't own a CAC card, thus this is almost impossible for me to validate if this would work. 
Did you try to use the current user option when logging into your site?

**Comment by bramdejager** [comment]
Closing the issue, clean-up (issue expired).
