### ISSUE TITLE
Create a chocolatey package for easy installation

### ISSUE THREAD

**Issue by nils-a** [bramdejager/spcb#102]
[chocolatey](https://chocolatey.org/) is a package manager for Windows. Using this is, it could be possible to install `spcb` using the following command:

```
choco install spcb
```

**Comment by nils-a** [comment]
I'd be willing to create and maintain such a package, if it is ok for you to have this.

Creation is currently blocked by #101

**Comment by bramdejager** [comment]
Closing the issue, clean-up (issue expired).

**Comment by nils-a** [comment]
I'm still fully prepared and willing to create and maintain a spcb package in the chocolatey community repository, if that's ok with you - and if we can get around #101, which is blocking this.
