### ISSUE TITLE
Would it be possible to add the "comments" list?

### ISSUE THREAD

**Issue by nils-a** [bramdejager/spcb#103]
I see some hidden lists are displayed while others are not.
I guess that's because some hidden lists are "known" while others are not.

Would it be possible to add the hidden "comments" list? It's always (well, in 2019 at least) named `Comments.30017244-8B12-4607-9D41-89A859BD352D`

**Comment by bramdejager** [comment]
If Comments is not a normal SharePoint list (as seen under the "Site Contents"), it will not show up in the SPCB. The SPCB uses the CSOM to retrieve its lists. 

Can you add some more detail on where to find the Comments list? I can have a look at it.

**Comment by nils-a** [comment]
Sorry. 
Digging deeper into it I see that comments are stored in the `DocComments` table. No way to access them all using CSOM.
