### ISSUE TITLE
Error when connecting to SP2019 On-premises

### ISSUE THREAD

**Issue by guilhermegara** [bramdejager/spcb#105]
![image](https://user-images.githubusercontent.com/71990105/176253912-d1dfe5e9-4cec-4599-8791-1f1e68d70993.png)

**Comment by bramdejager** [comment]
Please provide me the logs for details, check out [Report a bug](https://github.com/bramdejager/spcb/blob/master/docs/ReportBug.md)

**Comment by bramdejager** [comment]
Closing the issue, no response (issue has expired).
