### ISSUE TITLE
SPBrowser.Globals exception

### ISSUE THREAD

**Issue by itskumail** [bramdejager/spcb#106]
I got error while opening app, "The type intializer for 'SPBrowser.Globals' threw an exception"

**Comment by hhooiveld** [comment]
I encounter the same!

**Comment by bramdejager** [comment]
Please provide me the logs for details, check out [Report a bug](https://github.com/bramdejager/spcb/blob/master/docs/ReportBug.md)

**Comment by bramdejager** [comment]
Closing the issue, clean-up.
