### ISSUE TITLE
Subwebs not visible by default

### ISSUE THREAD

**Issue by szkvorcsi** [bramdejager/spcb#107]
When adding a site the subwebs are not visible such as Regional Setting, Site Columns, Site Features etc. 
![sp](https://github.com/bramdejager/spcb/assets/136806725/f681ec51-f14a-4028-a5d2-5244fb77296e)

**Comment by bramdejager** [comment]
It seems you had an issue, this one is resolved in [release v.19](https://github.com/bramdejager/spcb/releases/tag/v4.19) and up. Please check that out!
