### ISSUE TITLE
The application does not work

### ISSUE THREAD

**Issue by sdudnic-ingerop** [bramdejager/spcb#110]
Downloaded, opened, MS says is not a safe exe. 
Opened anyway, 

Tried to add tenant got 403 forbidden.

Tried to add a new site, Auth mode "Web Browser", it fails

> _SharePoint Online Client Browser_
> The property or field 'Title' has not been initialized. It has not been requested or the request has not been executed. It may need to be explicitly requested. 

after that we see this

![image](https://github.com/bramdejager/spcb/assets/148953528/81f28dcb-8e26-4252-a2ca-d99207e2996d)

SharePoint Online authentication does not work either, it says bad pasword, but I verified multiple account names with valid passwords and the connection fails with bad sign-in name or password error that is not true.

The application is not usable.

**Comment by garbb** [comment]
I have the same issue unfortunately.

**Comment by bramdejager** [comment]
Did quick research on the issue and I'm able to replicate the issue. Most of the times I'm the Owner of a site and have the permissions to request its data. It seems when you are not an Owner results in this issue. 

I'll have a look what I can do to resolve this.

**Comment by bramdejager** [comment]
Found the part of the code where things started to fall down, and resolved this issue. This should work now with [release v4.19](https://github.com/bramdejager/spcb/releases/tag/v4.19) and up! Enjoy.
