### ISSUE TITLE
Can't load a sub site as a site when trying to add it.

### ISSUE THREAD

**Issue by onad31** [bramdejager/spcb#112]
I'm not the proprietary of the company site but I own a sub site that they provided, I can't add it as it is trying to load the main site which I don't have access to.
[SPCB-HPE-5CG2064R0X-20240905.log](https://github.com/user-attachments/files/16900403/SPCB-HPE-5CG2064R0X-20240905.log)

**Comment by bramdejager** [comment]
Hi @onad31, I checked your logs and I see you are adding a site collection which is not reflected by the URL you are entering. Just to be sure, can you add a URL like https://company.sharepoint.com/sites/site? 

The subweb should show up underneath "Webs" node. Hope this helps!

**Comment by bramdejager** [comment]
Closing the issue, clean-up.
