### ISSUE TITLE
Source code of tool is not in github

### ISSUE THREAD

**Issue by stevebeauge** [bramdejager/spcb#65]
Hello,

Unless I've missed something, the github repo only contains the source code in a zip file in release tabs.

What about putting the source in github, in order to allow forking and helping building the tool (which has a great potential).

thanks

**Comment by bramdejager** [comment]
For now the sources code resides somewhere else. If you would like particular features or have requests, please let me know.

**Comment by t9mike** [comment]
Please consider putting source on Github. I am wanted to review code for example of how to use Windows Authentication to login to on-premises SP server. I downloaded via CodePlex archive. It was frustrating, however, as I first tried downloading source via https://github.com/bramdejager/spcb/releases/tag/v1.14, but that is just the github source.

At the least consider adding a very visible note about no updated source code and point to CodePlex archive in README.md and also mention no source in headline.

**Comment by t9mike** [comment]
FYI, reviewing source gave me hint I needed:

ccontext.Credentials = CredentialCache.DefaultNetworkCredentials;

**Comment by tegmos** [comment]
Any plans for this to happen still?  Very useful and desirable tool, but I want to be able to read and modify source. How/where can we get latest?
