### ISSUE TITLE
SP 2010

### ISSUE THREAD

**Issue by gbminnock** [bramdejager/spcb#70]
Hi,

Looking for the SP 2010 release. Is it still available?

Thanks

**Comment by bramdejager** [comment]
Hi, I added the SharePoint 2010 Client Browser to the releases list for archiving purpose. You can download this release here: [download SPCB v0.6](https://github.com/bramdejager/spcb/releases/tag/v0.6). Have fun!

**Comment by gbminnock** [comment]
thanks brandejager!
