### ISSUE TITLE
Keep getting an error (429)

### ISSUE THREAD

**Issue by alexandrualexe** [bramdejager/spcb#71]
When I try to add a new site collection to SharePoint Online Client Browser i keep receiving an error "The remote server returned an error: (429). Object reference not set to an instance of an object".

After multiple attempts the site collection is added, but after that when I try to browse it, I get the same error.

**Comment by bramdejager** [comment]
Hi, thanks for filing an issue. I need some more information, can you download the latest version of SPCB tool and follow instructions on the [Report a Bug](https://github.com/bramdejager/spcb/blob/master/docs/ReportBug.md) page?

**Comment by bramdejager** [comment]
Closing issue, no feedback. If issue is still valid, please let me know.
