### ISSUE TITLE
Error on adding sites

### ISSUE THREAD

**Issue by eamps** [bramdejager/spcb#72]
Hi Bram,

Apologies if I am not doing the right thing.  This is my first time of using the solution but I am trying to add a Site but I am getting the attached error.   Hope you can help.

Best regards,

EAmps

![image](https://user-images.githubusercontent.com/36665669/36425353-723d08b4-163e-11e8-98fb-c536d8ea3760.png)

**Comment by bramdejager** [comment]
Hi, thanks for filing an issue. I need some more information, can you download the latest version of SPCB tool and follow instructions on the [Report a Bug](https://github.com/bramdejager/spcb/blob/master/docs/ReportBug.md) page?

**Comment by bramdejager** [comment]
Closing issue, no feedback
