### ISSUE TITLE
Virus detection on spcb.exe

### ISSUE THREAD

**Issue by Mop3D** [bramdejager/spcb#74]
Hello Bram,
I still get the virus alarm on the latest spcb.exe (v3.4.1). 
It reports Luhe.Fiha.A Virus.
We have AVG Anti Virus running.
For that reason unfortunatly I can't use spcb because the company antivirus policy.

Best regards,
Martin

**Comment by bramdejager** [comment]
Thanks for reporting this and I'm sorry to hear this is blocking you, it seems the AVG engine is labeling the SPCB.exe as a virus. I have had this issue before. Back then I did not find a resolution for it. So, for now I don't really have an answer. Will see if I can provide a solution, but it might take a while.

**Comment by Mop3D** [comment]
Perhaps you can get it whitelisted.
There is a service web site for that:
https://secure.avg.com/submit-sample

**Comment by Mop3D** [comment]
I contacted AVG and told them about the problem.
It seems they added the app to the whitelist.
I will check this when I got the new AVG signature database.

Here the answer from AVG:

Hello , 

Thank you for contacting AVG.
Your request for whitelisting was processed and all files were added to our whitelist.
You can also check the following articles about AVG virus policy to avoid future detection: AVG Clean Guidelines.
Thank you
Best regards, 

AVG Customer Care

**Comment by Mop3D** [comment]
I got the new virus pattern database and SPCM.exe is no longer reported as infected.
So we can close this issue.

**Comment by bramdejager** [comment]
@Mop3D, a very big thank you! Great work and thumbs up for AVG.
