### ISSUE TITLE
The type initializer for 'SPBrowser.Globals' threw an exception

### ISSUE THREAD

**Issue by waltsully** [bramdejager/spcb#75]
I've downloaded and unzipped to a folder in Program File (x86) made a shortcut to the exe and no luck having the tool start-up.
![sp manager install error](https://user-images.githubusercontent.com/33215029/38138219-a6a8170c-33f7-11e8-8407-1aff1c760726.PNG)

**Comment by bramdejager** [comment]
Hi, thanks for filing an issue. I need some more information, can you download the latest version of SPCB tool and follow instructions on the [Report a Bug](https://github.com/bramdejager/spcb/blob/master/docs/ReportBug.md) page?

**Comment by waltsully** [comment]
Bram, took the https://github.com/bramdejager/spcb/releases/tag/v3.4.1 it started and works beautifly. Thanks for this nifty tool!  

![spcb tool screenshot](https://user-images.githubusercontent.com/33215029/38508044-2107c708-3bec-11e8-87cb-f939cc58721b.PNG)
