### ISSUE TITLE
Not responding immediately after program start

### ISSUE THREAD

**Issue by Crispify** [bramdejager/spcb#79]
Hi,

Version 3.6 hangs as soon as the splash screen closes. No logging file appears.
Same for version 3.5, only then the following logging is generated:

Time;Machine;Process;Version;Category;EventId;Level;Correlation;Message
17-05-2018 13:39:30.468;XPS-LENNERT;SPCB.exe;3.5.0.0;General;0;Information;e4a0056c-1928-4ee1-9ce5-ac77827cc000;Telemetry initiated with session Id ca050171-acac-4d4d-9203-a5e2474ee318 for user 4d5f52fc-a2ea-4c4c-8b27-4cad599d8978
17-05-2018 13:39:30.481;XPS-LENNERT;SPCB.exe;3.5.0.0;General;0;Information;e4a0056c-1928-4ee1-9ce5-ac77827cc000;Machine finger print: 8a25-****
17-05-2018 13:39:30.489;XPS-LENNERT;SPCB.exe;3.5.0.0;General;0;Information;e4a0056c-1928-4ee1-9ce5-ac77827cc000;Initialize application SharePoint Online Client Browser v3.5.0.0 (SPCB.exe) on Microsoft Windows NT 6.2.9200.0 (Win32NT) 
17-05-2018 13:39:30.502;XPS-LENNERT;SPCB.exe;3.5.0.0;General;0;Information;e4a0056c-1928-4ee1-9ce5-ac77827cc000;Truncating log files, keep last 10 log files.
17-05-2018 13:39:30.511;XPS-LENNERT;SPCB.exe;3.5.0.0;General;0;Information;e4a0056c-1928-4ee1-9ce5-ac77827cc000;Program arguments are: 
![2018-05-17 13_43_30-new issue bramdejager_spcb - firefox developer edition]

(https://user-images.githubusercontent.com/4930747/40175476-83ad08f0-59d8-11e8-8213-45892fd60a99.png)

**Comment by Crispify** [comment]
Version 3.7 behaves the same as 3.6.

Run exe -> shows loading screen, creates config file, opens a blank windows like the screenshot in my original post, also takes 25% CPU. No logfile is created. 

![2018-05-22 22_24_40-clipboard](https://user-images.githubusercontent.com/4930747/40388153-ffb1a994-5e0e-11e8-8a1b-04153e039f0c.png)

Maybe it's my Windows 10 Insider Preview 17666.1000 (rs_prerelease)?

**Comment by bramdejager** [comment]
The log files are located in your local profile, under C:\Users\username\AppData\Roaming\SPCB\Logs. Please check out that location. It has valuable information to do troubleshooting. 

With regards to the W10 insiders preview, no clue. I'm running the 1803 build and works. Have not heard from others with similar experience. Can you validate on another system?

**Comment by Crispify** [comment]
Works on other machines, just not on mine.

Time;Machine;Process;Version;Category;EventId;Level;Correlation;Message
24-05-2018 16:17:43.341;XPS-LENNERT;SPCB.exe;3.7.0.0;General;0;Information;f28aa136-4114-4ffe-a165-b3aa98d24d2d;Telemetry initiated with session Id c4f3c268-ed3e-4202-8c11-bdadb1144c08 for user 4d5f52fc-a2ea-4c4c-8b27-4cad599d8978
24-05-2018 16:17:43.356;XPS-LENNERT;SPCB.exe;3.7.0.0;General;0;Information;f28aa136-4114-4ffe-a165-b3aa98d24d2d;Machine finger print: 8a25-***
24-05-2018 16:17:43.365;XPS-LENNERT;SPCB.exe;3.7.0.0;General;0;Information;f28aa136-4114-4ffe-a165-b3aa98d24d2d;Initialize application SharePoint Online Client Browser v3.7.0.0 (SPCB.exe) on Microsoft Windows NT 6.2.9200.0 (Win32NT) 
24-05-2018 16:17:43.378;XPS-LENNERT;SPCB.exe;3.7.0.0;General;0;Information;f28aa136-4114-4ffe-a165-b3aa98d24d2d;Truncating log files, keep last 10 log files.
24-05-2018 16:17:43.386;XPS-LENNERT;SPCB.exe;3.7.0.0;General;0;Information;f28aa136-4114-4ffe-a165-b3aa98d24d2d;Program arguments are: 
24-05-2018 16:17:43.850;XPS-LENNERT;SPCB.exe;3.7.0.0;General;0;Verbose;f28aa136-4114-4ffe-a165-b3aa98d24d2d;New correlation, calling method: MainBrowser_VisibleChanged
24-05-2018 16:17:43.867;XPS-LENNERT;SPCB.exe;3.7.0.0;General;0;Verbose;819de720-c66a-49e0-ab82-2d9f487d4817;New correlation, calling method: tvSite_AfterSelect
24-05-2018 16:17:43.900;XPS-LENNERT;SPCB.exe;3.7.0.0;General;0;Verbose;f1763f3c-dec7-4599-9c17-87269a3fcd31;New correlation, calling method: MainBrowser_Shown

**Comment by LuboSta** [comment]
Having same issues , tried to disable firewals , move to other folders , run as administrators... Have insider preview , visual studio , SP SDK and other stuff installed , Log is attached , but in general it simply get freeze while loading not showing even menu just empty window.  I give it solid 15 min and no change. CPU 25-30 %  (assume single thread so something in loop maybe ? ). Time;Machine;Process;Version;Category;EventId;Level;Correlation;Message
07-06-2018 23:37:17.649;DESKTOP-TAIOBSL;SPCB.exe;3.7.0.0;General;0;Information;bb1e5976-3557-40da-b4b9-19b8b17c5a34;Telemetry initiated with session Id 1a3996c2-8b79-44c8-9e01-5e8ef1d73fd6 for user 0cc27489-df83-418e-bfbd-589e972e788d
07-06-2018 23:37:17.665;DESKTOP-TAIOBSL;SPCB.exe;3.7.0.0;General;0;Information;bb1e5976-3557-40da-b4b9-19b8b17c5a34;Machine finger print: c9a5-76b3-ffec-f8cd-061f-2f60-0537-e0f5
07-06-2018 23:37:17.681;DESKTOP-TAIOBSL;SPCB.exe;3.7.0.0;General;0;Information;bb1e5976-3557-40da-b4b9-19b8b17c5a34;Initialize application SharePoint Online Client Browser v3.7.0.0 (SPCB.exe) on Microsoft Windows NT 6.2.9200.0 (Win32NT) 
07-06-2018 23:37:17.696;DESKTOP-TAIOBSL;SPCB.exe;3.7.0.0;General;0;Information;bb1e5976-3557-40da-b4b9-19b8b17c5a34;Truncating log files, keep last 10 log files.
07-06-2018 23:37:17.696;DESKTOP-TAIOBSL;SPCB.exe;3.7.0.0;General;0;Information;bb1e5976-3557-40da-b4b9-19b8b17c5a34;Program arguments are: 
07-06-2018 23:42:45.215;DESKTOP-TAIOBSL;SPCB.exe;3.7.0.0;General;0;Information;33f0500b-3bfb-40ed-8927-7b94868277bb;Telemetry initiated with session Id db948326-8c72-4dae-b2de-92f6b6880705 for user 0cc27489-df83-418e-bfbd-589e972e788d
07-06-2018 23:42:45.231;DESKTOP-TAIOBSL;SPCB.exe;3.7.0.0;General;0;Information;33f0500b-3bfb-40ed-8927-7b94868277bb;Machine finger print: c9a5-76b3-ffec-f8cd-061f-2f60-0537-e0f5
07-06-2018 23:42:45.231;DESKTOP-TAIOBSL;SPCB.exe;3.7.0.0;General;0;Information;33f0500b-3bfb-40ed-8927-7b94868277bb;Initialize application SharePoint Online Client Browser v3.7.0.0 (SPCB.exe) on Microsoft Windows NT 6.2.9200.0 (Win32NT) 
07-06-2018 23:42:45.247;DESKTOP-TAIOBSL;SPCB.exe;3.7.0.0;General;0;Information;33f0500b-3bfb-40ed-8927-7b94868277bb;Truncating log files, keep last 10 log files.
07-06-2018 23:42:45.247;DESKTOP-TAIOBSL;SPCB.exe;3.7.0.0;General;0;Information;33f0500b-3bfb-40ed-8927-7b94868277bb;Program arguments are: 
07-06-2018 23:47:55.724;DESKTOP-TAIOBSL;SPCB.exe;3.7.0.0;General;0;Information;a370e2c0-4b6b-4501-8a34-90458da735cd;Telemetry initiated with session Id 5e9cebc9-e95f-46ba-a613-7835154ea3d6 for user 0cc27489-df83-418e-bfbd-589e972e788d
07-06-2018 23:47:55.740;DESKTOP-TAIOBSL;SPCB.exe;3.7.0.0;General;0;Information;a370e2c0-4b6b-4501-8a34-90458da735cd;Machine finger print: c9a5-76b3-ffec-f8cd-061f-2f60-0537-e0f5
07-06-2018 23:47:55.740;DESKTOP-TAIOBSL;SPCB.exe;3.7.0.0;General;0;Information;a370e2c0-4b6b-4501-8a34-90458da735cd;Initialize application SharePoint Online Client Browser v3.7.0.0 (SPCB.exe) on Microsoft Windows NT 6.2.9200.0 (Win32NT) 
07-06-2018 23:47:55.755;DESKTOP-TAIOBSL;SPCB.exe;3.7.0.0;General;0;Information;a370e2c0-4b6b-4501-8a34-90458da735cd;Truncating log files, keep last 10 log files.
07-06-2018 23:47:55.786;DESKTOP-TAIOBSL;SPCB.exe;3.7.0.0;General;0;Information;a370e2c0-4b6b-4501-8a34-90458da735cd;Program arguments are:

**Comment by eBentl** [comment]
Having the same issue with version 3.7 and version 4.0
Currently running Windows 10 1809, same issue experienced with 1803
Not sure where the logs are stored sorry but same issue as the two users above

**Comment by eBentl** [comment]
Interestingly my CPU usage is remaining relatively low but it is thrashing my memory - climbs up to about 10GB where it hits 100% used, drops down to about 3GB and climbs up again

![image](https://user-images.githubusercontent.com/43974241/46639792-13b54a00-cbb4-11e8-9da1-a66305f95002.png)

**Comment by onidaR** [comment]
Yes, I have same issues with 4.0 and 3.8.
Can you help me to fix this issue?
Thanks.

**Comment by eBentl** [comment]
Forgot to come back and respond, the machine I was using had a number of issues, got it replaced (same model and everything) and no longer have the issue

**Comment by onidaR** [comment]
This is great news! That explains why it's not working for me, while it does for my colleague...
Thanks again. Keep going.. :)

**Comment by bramdejager** [comment]
Check out the new [releases](https://github.com/bramdejager/spcb/releases), these contain the fix for this interesting issue... 
Please let me know if this fixed your problems?
