### ISSUE TITLE
'Modern' site collections not showing up

### ISSUE THREAD

**Issue by alexlushsevernunival** [bramdejager/spcb#81]
Using the 'classic' SharePoint Admin Centre. I see exactly the same site collections listing in SPCB, however if I use the new 'modern' SharePoint Admin Centre (https://techcommunity.microsoft.com/t5/SharePoint-Blog/Introducing-the-new-SharePoint-Admin-Center/ba-p/70294), I see a load of additional 'modern' site collections showing up that are not shown in the SPCB.

The 'modern' sites collections are created directly in SPO or provisioned via Outlook Groups or MS Teams.

It would be great to see ALL the site collections appear under the site collections node if this is possible.

**Comment by bramdejager** [comment]
Thanks for the feedback. I would need to look into that.

**Comment by nikolayyordanov** [comment]
Having the same issue with version 4.1. I can connect to individual "modern" site collections but cannot see them within the tenant.

**Comment by SamFoster** [comment]
BUMP! Any news on this ? 

Loving the tool, would be sweet if it iterated through the modern site collections in a tenant...

Keep up the good work!

Sam

**Comment by bramdejager** [comment]
Working on supporting both the Modern Sites and OneDrive for Business sites. I expect to release early next month.

**Comment by bramdejager** [comment]
Finally been able to get the release out, check out the latest SharePoint Online Client Browser release. 
Download [SharePoint Online Client Browser v4.3](https://github.com/bramdejager/spcb/releases/tag/v4.3)
