### ISSUE TITLE
SP2016 Client Browser v 2.9 : Declared as a risk from Symantec EndPoint Protection

### ISSUE THREAD

**Issue by cangot** [bramdejager/spcb#82]
Risk : WS.Reputation.1

See attached screenshot:
![symantec_risklog](https://user-images.githubusercontent.com/16799352/40920744-bda02dc4-680d-11e8-9cd3-d1aa1287b599.png)

**Comment by bramdejager** [comment]
Duplicate entry, see issue number #83 for more information. Closing duplicate issue.
