### ISSUE TITLE
Error when trying to expand "Items" in subsites

### ISSUE THREAD

**Issue by schoier** [bramdejager/spcb#84]
Hi, 
I'm unable to expand the Items node in lists in subsites. I get an error saying "List does not exist [...]". Actually it's in Swedish but i think it's a good translation :)

**Comment by markjjordan** [comment]
Me too.

![image](https://user-images.githubusercontent.com/8918996/47359196-162aa000-d69a-11e8-9d8b-7be089ade11d.png)

![image](https://user-images.githubusercontent.com/8918996/47359224-2b9fca00-d69a-11e8-9881-b19fbec07859.png)

**Comment by markjjordan** [comment]
I'm also getting the following on another library:

![image](https://user-images.githubusercontent.com/8918996/47359368-93eeab80-d69a-11e8-9d5e-7d21667e816f.png)


![image](https://user-images.githubusercontent.com/8918996/47359343-86392600-d69a-11e8-83f7-0b0759faed87.png)

**Comment by bmcomp** [comment]
Also seeing this when expanding Lists within a subsite.  Error "Cannot complete this action.  Please try again."

**Comment by schoier** [comment]
29-11-2018 08:58:27.341;DESKTOP-REMOVED;SPCB.exe;4.1.0.0;General;0;Information;0a6e1d89-c196-48ba-81b9-8559f5ad6b32;Configuration saved
29-11-2018 08:58:31.481;DESKTOP-REMOVED;SPCB.exe;4.1.0.0;General;0;Verbose;0a6e1d89-c196-48ba-81b9-8559f5ad6b32;New correlation, calling method: tvSite_MouseDown
29-11-2018 08:58:34.212;DESKTOP-REMOVED;SPCB.exe;4.1.0.0;General;0;Verbose;98d48ad8-850f-43a5-90ed-3cc9102b5f31;New correlation, calling method: tvSite_MouseDown
29-11-2018 08:58:34.328;DESKTOP-REMOVED;SPCB.exe;4.1.0.0;General;0;Verbose;347182bc-a26e-4167-990a-0b6156feaf87;New correlation, calling method: tvSite_AfterSelect
29-11-2018 08:58:36.743;DESKTOP-REMOVED;SPCB.exe;4.1.0.0;General;0;Verbose;aef12240-ee34-43b8-a97f-20ba46cb64a6;New correlation, calling method: tvSite_MouseDown
29-11-2018 08:58:36.850;DESKTOP-REMOVED;SPCB.exe;4.1.0.0;General;0;Verbose;bc46f4f6-a151-4482-a367-5b9ec882651d;New correlation, calling method: tvSite_AfterExpand
29-11-2018 08:58:37.402;DESKTOP-REMOVED;SPCB.exe;4.1.0.0;TreeViewLoader;0;Verbose;879a2e05-fc71-4b6a-90ff-f18690d74fc3;Added Microsoft.SharePoint.Client.ListItem node '11, Anbud'
29-11-2018 08:58:37.405;DESKTOP-REMOVED;SPCB.exe;4.1.0.0;TreeViewLoader;0;Verbose;879a2e05-fc71-4b6a-90ff-f18690d74fc3;Added Microsoft.SharePoint.Client.ListItemComplianceInfo node 'Compliance Info'
29-11-2018 08:58:37.407;DESKTOP-REMOVED;SPCB.exe;4.1.0.0;TreeViewLoader;0;Verbose;879a2e05-fc71-4b6a-90ff-f18690d74fc3;Added Microsoft.SharePoint.Client.ObjectSharingInformation node 'Sharing Info'
29-11-2018 08:58:37.411;DESKTOP-REMOVED;SPCB.exe;4.1.0.0;TreeViewLoader;0;Verbose;879a2e05-fc71-4b6a-90ff-f18690d74fc3;Added Microsoft.SharePoint.Client.ListItem node '12, Anbudsutvärdering'
29-11-2018 08:58:37.413;DESKTOP-REMOVED;SPCB.exe;4.1.0.0;TreeViewLoader;0;Verbose;879a2e05-fc71-4b6a-90ff-f18690d74fc3;Added Microsoft.SharePoint.Client.ListItemComplianceInfo node 'Compliance Info'
29-11-2018 08:58:37.413;DESKTOP-REMOVED;SPCB.exe;4.1.0.0;TreeViewLoader;0;Verbose;879a2e05-fc71-4b6a-90ff-f18690d74fc3;Added Microsoft.SharePoint.Client.ObjectSharingInformation node 'Sharing Info'
29-11-2018 08:58:37.413;DESKTOP-REMOVED;SPCB.exe;4.1.0.0;TreeViewLoader;0;Verbose;879a2e05-fc71-4b6a-90ff-f18690d74fc3;Added Microsoft.SharePoint.Client.ListItem node '13, Entreprenadbeställning'
29-11-2018 08:58:37.413;DESKTOP-REMOVED;SPCB.exe;4.1.0.0;TreeViewLoader;0;Verbose;879a2e05-fc71-4b6a-90ff-f18690d74fc3;Added Microsoft.SharePoint.Client.ListItemComplianceInfo node 'Compliance Info'
29-11-2018 08:58:37.413;DESKTOP-REMOVED;SPCB.exe;4.1.0.0;TreeViewLoader;0;Verbose;879a2e05-fc71-4b6a-90ff-f18690d74fc3;Added Microsoft.SharePoint.Client.ObjectSharingInformation node 'Sharing Info'
29-11-2018 08:58:37.429;DESKTOP-REMOVED;SPCB.exe;4.1.0.0;TreeViewLoader;0;Verbose;879a2e05-fc71-4b6a-90ff-f18690d74fc3;Added Microsoft.SharePoint.Client.ListItem node '14, Konsultbeställning'
29-11-2018 08:58:37.429;DESKTOP-REMOVED;SPCB.exe;4.1.0.0;TreeViewLoader;0;Verbose;879a2e05-fc71-4b6a-90ff-f18690d74fc3;Added Microsoft.SharePoint.Client.ListItemComplianceInfo node 'Compliance Info'
29-11-2018 08:58:37.429;DESKTOP-REMOVED;SPCB.exe;4.1.0.0;TreeViewLoader;0;Verbose;879a2e05-fc71-4b6a-90ff-f18690d74fc3;Added Microsoft.SharePoint.Client.ObjectSharingInformation node 'Sharing Info'
29-11-2018 08:58:37.429;DESKTOP-REMOVED;SPCB.exe;4.1.0.0;TreeViewLoader;0;Verbose;879a2e05-fc71-4b6a-90ff-f18690d74fc3;Added Microsoft.SharePoint.Client.ListItem node '15, Tilldelning'
29-11-2018 08:58:37.429;DESKTOP-REMOVED;SPCB.exe;4.1.0.0;TreeViewLoader;0;Verbose;879a2e05-fc71-4b6a-90ff-f18690d74fc3;Added Microsoft.SharePoint.Client.ListItemComplianceInfo node 'Compliance Info'
29-11-2018 08:58:37.445;DESKTOP-REMOVED;SPCB.exe;4.1.0.0;TreeViewLoader;0;Verbose;879a2e05-fc71-4b6a-90ff-f18690d74fc3;Added Microsoft.SharePoint.Client.ObjectSharingInformation node 'Sharing Info'
29-11-2018 08:58:40.607;DESKTOP-REMOVED;SPCB.exe;4.1.0.0;General;0;Exception;879a2e05-fc71-4b6a-90ff-f18690d74fc3;Listan finns inte.

Sidan som du valde innehåller en lista som inte finns. Den kan ha tagits bort av en annan användare.
29-11-2018 08:58:40.610;DESKTOP-REMOVED;SPCB.exe;4.1.0.0;General;0;Exception;879a2e05-fc71-4b6a-90ff-f18690d74fc3;Microsoft.SharePoint.Client.ServerException: Listan finns inte.
29-11-2018 08:58:40.612;DESKTOP-REMOVED;SPCB.exe;4.1.0.0;General;0;Exception;879a2e05-fc71-4b6a-90ff-f18690d74fc3;
29-11-2018 08:58:40.615;DESKTOP-REMOVED;SPCB.exe;4.1.0.0;General;0;Exception;879a2e05-fc71-4b6a-90ff-f18690d74fc3;Sidan som du valde innehåller en lista som inte finns. Den kan ha tagits bort av en annan användare.
29-11-2018 08:58:40.621;DESKTOP-REMOVED;SPCB.exe;4.1.0.0;General;0;Exception;879a2e05-fc71-4b6a-90ff-f18690d74fc3;   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
29-11-2018 08:58:40.621;DESKTOP-REMOVED;SPCB.exe;4.1.0.0;General;0;Exception;879a2e05-fc71-4b6a-90ff-f18690d74fc3;   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
29-11-2018 08:58:40.621;DESKTOP-REMOVED;SPCB.exe;4.1.0.0;General;0;Exception;879a2e05-fc71-4b6a-90ff-f18690d74fc3;   at Microsoft.SharePoint.Client.ClientContext.ExecuteQuery()
29-11-2018 08:58:40.621;DESKTOP-REMOVED;SPCB.exe;4.1.0.0;General;0;Exception;879a2e05-fc71-4b6a-90ff-f18690d74fc3;   at SPBrowser.NodeLoader.LoadItems(TreeNode parentNode, List list, MainForm form, NodeLoadType loadType, Boolean isRetry)

**Comment by bramdejager** [comment]
Thanks for the logs, I have been able to reproduce the issue on my end. Will work on a fix soon! Keep you posted.

**Comment by bramdejager** [comment]
Finally removed the Object Sharing Information from List Items which is causing this weird behavior. Not sure how to properly use that part of the CSOM. But by removing it (hopefully temporarily) the tool is working as expected. 

Please download the new [releases](https://github.com/bramdejager/spcb/releases) based on your usage scenario. Let me know if you have any questions?!

**Comment by schoier** [comment]
@bramdejager Sorry for late response, but i works perfect. Thank you!
