### ISSUE TITLE
DataGridView Error

### ISSUE THREAD

**Issue by djtrustgod** [bramdejager/spcb#87]
When accessing Change Log on a Site Pages library in SP Online library SPCB threw a DataGridView error.  
![image](https://user-images.githubusercontent.com/16434275/52671679-920e5980-2ed0-11e9-8fd1-7d4dc99749fc.png)

**Comment by bramdejager** [comment]
Hi, too bad you experienced issues. Can you download the latest version again and post the log files for reference? 

Please follow instructions on the [Report a Bug](https://github.com/bramdejager/spcb/blob/master/docs/ReportBug.md) page.

**Comment by bramdejager** [comment]
Closing the issue, clean-up.
