### ISSUE TITLE
Error on Adding Site Cltn

### ISSUE THREAD

**Issue by CJ1169** [bramdejager/spcb#88]
Hey Bram,
I'm having an issue with the SharePoint Online version (persistent across 4.2, 4.1, & 4.0)
The issue shows:
`The type of data at position 1185 is different than the one expected.`
Attached is a log file.
[SPCB-USMEN-C0GMQN2-20190312.log](https://github.com/bramdejager/spcb/files/2957371/SPCB-USMEN-C0GMQN2-20190312.log)
Strangely, the connection proceeds just fine when using the SharePoint 2019 version (although not formally compatible).
-Carter

**Comment by larnera** [comment]
Hiya. I'm seeing this same error message too. I'm on version 4.2.0.0 and on Windows 10. 

It worked fine a week or two ago for me, on my Windows 7 machine.

**Comment by bramdejager** [comment]
Hi, I saw similar issues on our end (from colleagues) too. Not sure if this is still the case or if it was a hick up of Office 365? Can you validate? 

And If you are still experiencing this, can you provide some more info? Please follow instructions on the [Report a Bug](https://github.com/bramdejager/spcb/blob/master/docs/ReportBug.md) page.

**Comment by CJ1169** [comment]
I tried two more sites with another computer. I had a different error this time.
`Object reference not set to an instance of an object.`
Attached is a log file.
[SPCB-CEEJAY-LAPTOP-20190326.log](https://github.com/bramdejager/spcb/files/3009154/SPCB-CEEJAY-LAPTOP-20190326.log)
This time it seemed to load the second site I tried.
However, I was not able to access the first subsite I tried.
Seems so far to be an entirely different error than before.

**Comment by CJ1169** [comment]
Notably, I tried opening sites again today and, without doing anything different, it loaded the site into SPOCB. It still failed with the above error when attempting to connect to a subsite of a site.
I believe it may have something to do with not having access to that primary site, but having access to the subsite.
As far as the original issue opened goes, it seems to have been a hiccup of O365 - I can connect to the original site as expected with no errors.

**Comment by bramdejager** [comment]
Seems the issue has resolved itself, looks like an update on the Office 365 side?! Will close it for now.
