### ISSUE TITLE
DataView Grid Error

### ISSUE THREAD

**Issue by DeanGross** [bramdejager/spcb#89]
[SPCB-USCVGNB30101-20190515.log](https://github.com/bramdejager/spcb/files/3184053/SPCB-USCVGNB30101-20190515.log)
here is the log file showing the errors i got when I clicked on the Change Log tab

**Comment by bramdejager** [comment]
It seems there is an issue with retrieving changes on List object. It has to do with retrieval of _RootFolderUrl_ property of _ChangeList_ object. This is a bit more complex than I would have hoped. Will look into it.

**Comment by bramdejager** [comment]
@DeanGross is it the same error as #87?

**Comment by bramdejager** [comment]
Closing the issue, clean-up.
