### ISSUE TITLE
Unable to add new tenant or sitecollection

### ISSUE THREAD

**Issue by Benny56** [bramdejager/spcb#93]
I Ave a fresh download stored at C:\Program Files (x86)\SharePoint.Online.Client.Browser.v4.7. I have used earlier versions installed on other computers without issues.
Now I cannot login anymore: "The sign-in name or password does not match…"
There are no issues using PowerShell.

**Comment by Benny56** [comment]
It turned out that connecting to SharePoint online with PowerShell works for me only using multifactor authentication (MFA) -> "Connect-SPOService -Url https://$orgName-admin.sharepoint.com". The command "Connect-SPOService -Url https://$orgName-admin.sharepoint.com -Credential $userCredential" returns the mentioned error message.

The button "Get your username" seems not to work.

**Comment by bramdejager** [comment]
Closing the issue, clean-up.
