### ISSUE TITLE
Not able to connect to Sharepoint Online

### ISSUE THREAD

**Issue by sathya-bhat** [bramdejager/spcb#94]
I have created a trial 3 month O365 account. I have granted all required permissions. When I try to connect to my office 365 tenant, it says 'This account credentials does not match in Microsoft account system. I do not have Azure account.
I can connect to the O365 using Postman with OAuth endpoint with same credentials. Here is the SPCB log fragment.

==========================

23-04-2020 16:35:27.189;W10-100438-01;SPCB.exe;4.7.0.0;General;0;Information;2b769cc7-b3d3-40bf-84b6-efeabf1fd916;Valide (execute) the ClientContext.
23-04-2020 16:35:29.689;W10-100438-01;SPCB.exe;4.7.0.0;General;0;Exception;2b769cc7-b3d3-40bf-84b6-efeabf1fd916;The sign-in name or password does not match one in the Microsoft account system.
23-04-2020 16:35:29.694;W10-100438-01;SPCB.exe;4.7.0.0;General;0;Exception;2b769cc7-b3d3-40bf-84b6-efeabf1fd916;Microsoft.SharePoint.Client.IdcrlException: The sign-in name or password does not match one in the Microsoft account system.
23-04-2020 16:35:29.696;W10-100438-01;SPCB.exe;4.7.0.0;General;0;Exception;2b769cc7-b3d3-40bf-84b6-efeabf1fd916;   at Microsoft.SharePoint.Client.Idcrl.IdcrlAuth.GetServiceToken(String securityXml, String serviceTarget, String servicePolicy)
23-04-2020 16:35:29.698;W10-100438-01;SPCB.exe;4.7.0.0;General;0;Exception;2b769cc7-b3d3-40bf-84b6-efeabf1fd916;   at Microsoft.SharePoint.Client.Idcrl.IdcrlAuth.GetServiceToken(String username, String password, String serviceTarget, String servicePolicy)
23-04-2020 16:35:29.700;W10-100438-01;SPCB.exe;4.7.0.0;General;0;Exception;2b769cc7-b3d3-40bf-84b6-efeabf1fd916;   at Microsoft.SharePoint.Client.Idcrl.SharePointOnlineAuthenticationProvider.GetAuthenticationCookie(Uri url, String username, SecureString password, Boolean alwaysThrowOnFailure, EventHandler`1 executingWebRequest)
23-04-2020 16:35:29.702;W10-100438-01;SPCB.exe;4.7.0.0;General;0;Exception;2b769cc7-b3d3-40bf-84b6-efeabf1fd916;   at Microsoft.SharePoint.Client.SharePointOnlineCredentials.GetAuthenticationCookie(Uri url, Boolean refresh, Boolean alwaysThrowOnFailure)
23-04-2020 16:35:29.704;W10-100438-01;SPCB.exe;4.7.0.0;General;0;Exception;2b769cc7-b3d3-40bf-84b6-efeabf1fd916;   at Microsoft.SharePoint.Client.ClientRuntimeContext.SetupRequestCredential(ClientRuntimeContext context, HttpWebRequest request)
23-04-2020 16:35:29.706;W10-100438-01;SPCB.exe;4.7.0.0;General;0;Exception;2b769cc7-b3d3-40bf-84b6-efeabf1fd916;   at Microsoft.SharePoint.Client.SPWebRequestExecutor.GetRequestStream()
23-04-2020 16:35:29.708;W10-100438-01;SPCB.exe;4.7.0.0;General;0;Exception;2b769cc7-b3d3-40bf-84b6-efeabf1fd916;   at Microsoft.SharePoint.Client.ClientContext.GetWebRequestExecutor()
23-04-2020 16:35:29.715;W10-100438-01;SPCB.exe;4.7.0.0;General;0;Exception;2b769cc7-b3d3-40bf-84b6-efeabf1fd916;   at Microsoft.SharePoint.Client.ClientContext.GetFormDigestInfoPrivate()
23-04-2020 16:35:29.717;W10-100438-01;SPCB.exe;4.7.0.0;General;0;Exception;2b769cc7-b3d3-40bf-84b6-efeabf1fd916;   at Microsoft.SharePoint.Client.ClientContext.EnsureFormDigest()
23-04-2020 16:35:29.719;W10-100438-01;SPCB.exe;4.7.0.0;General;0;Exception;2b769cc7-b3d3-40bf-84b6-efeabf1fd916;   at Microsoft.SharePoint.Client.ClientContext.ExecuteQuery()
23-04-2020 16:35:29.721;W10-100438-01;SPCB.exe;4.7.0.0;General;0;Exception;2b769cc7-b3d3-40bf-84b6-efeabf1fd916;   at SPBrowser.Entities.SiteAuthentication.InitClientContext()
23-04-2020 16:35:29.724;W10-100438-01;SPCB.exe;4.7.0.0;General;0;Exception;2b769cc7-b3d3-40bf-84b6-efeabf1fd916;   at SPBrowser.Entities.SiteAuthenticationCollection.Add(Uri url, String username, String password, AuthenticationMode authn)
23-04-2020 16:35:29.726;W10-100438-01;SPCB.exe;4.7.0.0;General;0;Exception;2b769cc7-b3d3-40bf-84b6-efeabf1fd916;   at SPBrowser.AddSiteForm.LoadSite()
23-04-2020 16:35:55.673;W10-100438-01;SPCB.exe;4.7.0.0;General;0;Information;2b769cc7-b3d3-40bf-84b6-efeabf1fd916;Initializing site collection (ClientContext) for https://mysite.sharepoint.com/.
23-04-2020 16:35:55.676;W10-100438-01;SPCB.exe;4.7.0.0;General;0;Information;2b769cc7-b3d3-40bf-84b6-efeabf1fd916;Using SharePoint Online credentials for user 'mysite@mysite.onmicrosoft.com'.
23-04-2020 16:35:55.678;W10-100438-01;SPCB.exe;4.7.0.0;General;0;Information;2b769cc7-b3d3-40bf-84b6-efeabf1fd916;Valide (execute) the ClientContext.
23-04-2020 16:37:43.329;W10-100438-01;SPCB.exe;4.7.0.0;General;0;Exception;2b769cc7-b3d3-40bf-84b6-efeabf1fd916;The sign-in name or password does not match one in the Microsoft account system.
23-04-2020 16:37:43.331;W10-100438-01;SPCB.exe;4.7.0.0;General;0;Exception;2b769cc7-b3d3-40bf-84b6-efeabf1fd916;Microsoft.SharePoint.Client.IdcrlException: The sign-in name or password does not match one in the Microsoft account system.
23-04-2020 16:37:43.333;W10-100438-01;SPCB.exe;4.7.0.0;General;0;Exception;2b769cc7-b3d3-40bf-84b6-efeabf1fd916;   at Microsoft.SharePoint.Client.Idcrl.IdcrlAuth.GetServiceToken(String securityXml, String serviceTarget, String servicePolicy)
23-04-2020 16:37:43.335;W10-100438-01;SPCB.exe;4.7.0.0;General;0;Exception;2b769cc7-b3d3-40bf-84b6-efeabf1fd916;   at Microsoft.SharePoint.Client.Idcrl.IdcrlAuth.GetServiceToken(String username, String password, String serviceTarget, String servicePolicy)
23-04-2020 16:37:43.337;W10-100438-01;SPCB.exe;4.7.0.0;General;0;Exception;2b769cc7-b3d3-40bf-84b6-efeabf1fd916;   at Microsoft.SharePoint.Client.Idcrl.SharePointOnlineAuthenticationProvider.GetAuthenticationCookie(Uri url, String username, SecureString password, Boolean alwaysThrowOnFailure, EventHandler`1 executingWebRequest)
23-04-2020 16:37:43.339;W10-100438-01;SPCB.exe;4.7.0.0;General;0;Exception;2b769cc7-b3d3-40bf-84b6-efeabf1fd916;   at Microsoft.SharePoint.Client.SharePointOnlineCredentials.GetAuthenticationCookie(Uri url, Boolean refresh, Boolean alwaysThrowOnFailure)
23-04-2020 16:37:43.341;W10-100438-01;SPCB.exe;4.7.0.0;General;0;Exception;2b769cc7-b3d3-40bf-84b6-efeabf1fd916;   at Microsoft.SharePoint.Client.ClientRuntimeContext.SetupRequestCredential(ClientRuntimeContext context, HttpWebRequest request)
23-04-2020 16:37:43.343;W10-100438-01;SPCB.exe;4.7.0.0;General;0;Exception;2b769cc7-b3d3-40bf-84b6-efeabf1fd916;   at Microsoft.SharePoint.Client.SPWebRequestExecutor.GetRequestStream()
23-04-2020 16:37:43.345;W10-100438-01;SPCB.exe;4.7.0.0;General;0;Exception;2b769cc7-b3d3-40bf-84b6-efeabf1fd916;   at Microsoft.SharePoint.Client.ClientContext.GetWebRequestExecutor()
23-04-2020 16:37:43.347;W10-100438-01;SPCB.exe;4.7.0.0;General;0;Exception;2b769cc7-b3d3-40bf-84b6-efeabf1fd916;   at Microsoft.SharePoint.Client.ClientContext.GetFormDigestInfoPrivate()
23-04-2020 16:37:43.349;W10-100438-01;SPCB.exe;4.7.0.0;General;0;Exception;2b769cc7-b3d3-40bf-84b6-efeabf1fd916;   at Microsoft.SharePoint.Client.ClientContext.EnsureFormDigest()
23-04-2020 16:37:43.351;W10-100438-01;SPCB.exe;4.7.0.0;General;0;Exception;2b769cc7-b3d3-40bf-84b6-efeabf1fd916;   at Microsoft.SharePoint.Client.ClientContext.ExecuteQuery()
23-04-2020 16:37:43.353;W10-100438-01;SPCB.exe;4.7.0.0;General;0;Exception;2b769cc7-b3d3-40bf-84b6-efeabf1fd916;   at SPBrowser.Entities.SiteAuthentication.InitClientContext()
23-04-2020 16:37:43.355;W10-100438-01;SPCB.exe;4.7.0.0;General;0;Exception;2b769cc7-b3d3-40bf-84b6-efeabf1fd916;   at SPBrowser.Entities.SiteAuthenticationCollection.Add(Uri url, String username, String password, AuthenticationMode authn)
23-04-2020 16:37:43.357;W10-100438-01;SPCB.exe;4.7.0.0;General;0;Exception;2b769cc7-b3d3-40bf-84b6-efeabf1fd916;   at SPBrowser.AddSiteForm.LoadSite()

**Comment by sebasky** [comment]
Same problem!

**Comment by PatrickGaul** [comment]
I used to be able to log in to my SharePoint Online site under my Microsoft 365 tenant, but I get the same issue here now. I am able to log into the tenant admin site and the SharePoint site collections with the same credentials that I'm using with the SharePoint Online Client Browser, but it simply won't log me in. It's claiming that "the sign-in name or password does not match one in the Microsoft account system".

**Comment by ThomasBomann** [comment]
I had the same issue. Disabling Security Defaults in the Azure portal made it possible for me to sign in.

https://aad.portal.azure.com/#blade/Microsoft_AAD_IAM/ActiveDirectoryMenuBlade/Properties

Click Manage security defaults link at the bottom

Set Enable Security Defaults to No

**Comment by bramdejager** [comment]
Closing the issue, clean-up.
