### ISSUE TITLE
Cannot sign in using MFA

### ISSUE THREAD

**Issue by arjohnson77** [bramdejager/spcb#95]
I have an admin account that uses MFA. The account is O365 only, not Windows / AD based. When trying to add a tenant, all options are disabled and it forces SharePoint Online authentication. When adding an individual site, I can change the authentication mode, however all options still fail for the user with MFA, but not a non-MFA user.

**Comment by fredupstair** [comment]
Same issue.

**Comment by WorTony** [comment]
@fredupstair - I have tried the ADFS option too but it's not working for me.

I enter my user id and password into the pop up dialog then click signin, the dialog box goes white and does nothing. After waiting for 5 or more minutes, I click the close button and the Connect to Site Collection dialog says "Could not load site. Please retry". 

I am logged into the site collection and I have the "don't ask for MFA for 14 days" option checked - subsequent browser logins dont require the MFA.

Any ideas as to what's going wrong?

**Comment by amischreiber** [comment]
Same issue here.

**Comment by amischreiber** [comment]
> Same issue, but solved using ADFS option instead Microsoft Office 365 Account.

If I am logged into two different Office 365 accounts it doesn't let me specify which one to use for ADFS and then uses the default which is not the correct one. :/

**Comment by kosist** [comment]
Same issue here.

**Comment by bramdejager** [comment]
Issue resolved with new releases.
