### ISSUE TITLE
FieldLink properties not initialized for SharePoint 2019 and SharePoint Online

### ISSUE THREAD

**Issue by gszdev** [bramdejager/spcb#96]
Hi @bramdejager, please can you add (load) the "ReadyOnly", "ShowInDisplayForm" and the "Displayname" properties of FieldLinks inside content types (site and list conten types).

Thanks.

Here are the error messages
The property or field 'DisplayName' has not been initialized. It has not been requested or the request has not been executed. It may need to be explicitly requested.
The property or field 'ReadOnly' has not been initialized. It has not been requested or the request has not been executed. It may need to be explicitly requested.
The property or field 'ShowInDisplayForm' has not been initialized. It has not been requested or the request has not been executed. It may need to be explicitly requested.

**Comment by bramdejager** [comment]
Hi, updated the SPCB tool and released new packages. This includes your request to load the additional properties. Have fun!
https://github.com/bramdejager/spcb/releases
