### ISSUE TITLE
Exception value can't be null 

### ISSUE THREAD

**Issue by WilliamZheng** [bramdejager/spcb#98]
When I expand the a site collection node, it throw "Value cannot be null. Parameter name: key".

**Comment by sidper** [comment]
Same issue. It worked until recently

**Comment by gszdev** [comment]
Hi @bramdejager,

I'm also faced with the same issue. The is not reproducable for all my site collections. I think the issue only happens on "newer" site collections.

Steps to reproduce:
- Create a new communication site
- Add the new site to SPCB

Here are some details from the SPCB log:

Microsoft.SharePoint.Client.**ServerException**: Value cannot be null.
Parameter name: key
at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
at Microsoft.SharePoint.Client.ClientContext.ExecuteQuery()
at **SPBrowser.Extentions.SiteExtentions.IsCurrentUserAdmin**(Site site)
at SPBrowser.NodeLoader.LoadWeb(TreeNode parentNode, Web web, MainForm form)
at SPBrowser.NodeLoader.LoadSite(TreeNode parentNode, ClientContext ctx, Site site, MainForm form, List`1 subwebs)


I don't know wether you can do something. 
Maybe some checking for NULL or RootWeb is initialized correctly may help.
Thx.

**Comment by imir-hoxha** [comment]
I am facing the same issue here.

**Comment by ismikhaylov** [comment]
Hi!
I have same issue, it works well two weeks ago

**Comment by bramdejager** [comment]
Thanks for the feedback. I’ll have a look at it. It seems not all sites face the issue. Some have and some don’t. Have not figured out what’s the difference.

Outlook voor iOS<https://aka.ms/o0ukef> downloaden
________________________________
Van: Iliya <notifications@github.com>
Verzonden: Friday, September 18, 2020 7:50:03 PM
Aan: bramdejager/spcb <spcb@noreply.github.com>
CC: Bram de Jager <bramdejager@outlook.com>; Mention <mention@noreply.github.com>
Onderwerp: Re: [bramdejager/spcb] Exception value can't be null (#98)


Hi!
I have same issue, it works well two weeks ago

**Comment by patrikhellgren** [comment]
I'm also seeing the same issue. @bramdejager you might want to have a look at the issue reported over in pnp/sp-dev-docs to see if this is related: https://github.com/SharePoint/sp-dev-docs/issues/6281
At least it is the same error message and seems to have started on the 9th of september so the timing is also the same.

**Comment by slavag** [comment]
Same issue here, we see this in lot of our customers, not all , but many (thousands).
Started at Sep 9.

**Comment by bramdejager** [comment]
Checked a bunch of conditions, but I'm not able to track back any weird incorrect conditions. I have the same issue and error message on different tenants. But not all. Some tenants seem to work fine and don't cause any issues. I updated the CSOM to the latest version (August) but did not resolve the issue. I validated server/farm versions, but all were on version 16.0.20509.12005.

**Comment by jansenbe** [comment]
@bramdejager : I'm also seeing this issue and can reproduce with creating a private channel in Teams and then connecting to that site using SPCB. Doing a Fiddler trace showed the 4th CSOM call after connecting a site collection fails with a server error. I did pull the ULS logs for that error and noticed a server side JSON serialization issue (which clearly is a bug). Looking at the stacktrace in the ULS log the error seems to originate from loading the ThemeInfo property: can you try to exclude that property and see if it fixes things?

**Comment by jansenbe** [comment]
@bramdejager : internal thread started on this, will keep you all posted of the outcome

**Comment by bramdejager** [comment]
@jansenbe it lookes excluding the ThemeInfo object is solving the issue. I'll release an intermediate release as a workaround.

**Comment by phill29** [comment]
Any movement on this? Is _api/web/ThemeInfo expected to work again anytime soon?

**Comment by bramdejager** [comment]
Released a temporary release as a workaround, please see [release SPCB v4.10.1](https://github.com/bramdejager/spcb/releases/tag/v4.10.1). This release excludes the ThemeInfo object from loading.

**Comment by bramdejager** [comment]
Closing the issue, clean-up (issue solved).
